### ISSUE TITLE
--------------

### ISSUE THREAD

**Issue by kwekwwelkwelk** [ET-Lang/ET#5]
---------------

**Comment by BaseMax** [comment]
Hey Pedro Guilherme @pglapds,

Same as "<<" ">>" operator in C++?

- http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Companion/cxx_crib/input_output.html
- http://www.cplusplus.com/doc/tutorial/operators/

Regards,
Max.

**Comment by pglapds** [comment]
> Hey Pedro Guilherme @pglapds,
> 
> Same as "<<" ">>" operator in C++?
> 
> * http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Companion/cxx_crib/input_output.html
> * http://www.cplusplus.com/doc/tutorial/operators/
> 
> Regards,
> Max.

Would it be possible?

**Comment by BaseMax** [comment]
> Would it be possible?
Yeah, We can follow this. @pglapds 
But I not sure about it.

Because of the `<<`, `>>` operators used for shift-left, shift-right.
So it's not good when we use that for another purpose.

We require to better reasons to apply this change.
Remember the Semantic Analysis is important for a programming language.

**Comment by BaseMax** [comment]
> @start
> main:
>      url("test.txt","../new.txt") -> ("test.txt","../new.txt");
>      int url
> end

**Comment by pglapds** [comment]
> > main:
> > url("test.txt","../new.txt") -> ("test.txt","../new.txt");
> > int url
> > end
> 
> Can you explain your code? @pglapds
> 
> Current ET syntax :
> https://github.com/ET-Lang/STD/tree/master/file

```
main:
url("test.txt","../new.txt") -> ("test.txt","../new.txt");
int url
end
```
Move the file, move the folder from another file for example "test.txt"  and | or "/new.txt"

**Comment by pglapds** [comment]
I'm inspired by languages ​​like C++, PHP,  C,  Prolog. I would like to explain the use of the concept **"URL"** and the use of the symbol **"->** ... **"<-"**

**Comment by pglapds** [comment]
**What do you think?** I'm thinking of a new idea ir new syntax.  It would be interesting to have something different
