### ISSUE TITLE
Symbol Shell  '&'

### ISSUE THREAD

**Issue by pglapds** [ET-Lang/ET#7]
#### Symbol Shell  '&'

1. I thought of a symbol for the command line... I believe this symbol would be better for being new, different.

2. Common symbols: '>', '#', '>>', '$' ....

3. '&' is good... or... it's better now or now in my concept.

**Comment by BaseMax** [comment]
> 1. command line

// here is

**Comment by BaseMax** [comment]
> #### Symbol Shell '&'
> 1. I thought of a symbol for the command line... I believe this symbol would be better for being new, different.
> 2. Common symbols: '>', '#', '>>', '$' ....
> 3. '&' is good... or... it's better now or now in my concept.

Can you explain along with the example of your concept?
